feat: Horizontal Logo Generator
fossunited/logo-generator pull request #1
Opened 2024-01-15 17:42 UTC by rohansh-tty

Note: Since I took a fork from tinkerhub's logo generator repo, even their commit history is here.

- horizontal logo generator for FOSS United Clubs with Light and Dark Theme

2024-01-20 07:25 UTC, RiyaMathew-11 commented on index.html
> +    <title>FOSS United | Campus Logo Generator</title>
Use FOSS Club instead FOSS United. The heading could be FOSS Clubs' Logo Generator

2024-01-20 07:40 UTC, RiyaMathew-11 requested changes

2024-01-20 07:40 UTC, RiyaMathew-11 commented on index.html
> +                            <tspan id="logoName" class="name">RIT Kottayam</tspan>
Instead of RIT Kottayam - put Club Name as a generic term.

2024-01-20 07:40 UTC, RiyaMathew-11 commented on index.html
> +    <title>FOSS United | Campus Logo Generator</title>
Use FOSS Club instead FOSS United. The heading could be FOSS Clubs' Logo Generator

2024-01-20 07:40 UTC, RiyaMathew-11 commented on scripts/Horizontal Stacked Logo.svg
Move this file to /assets and change path, where referenced.

2024-01-20 07:40 UTC, RiyaMathew-11 commented on scripts/Horizontal Stacked Logo.svg
Change the naming of file to horizontal_lightlogo.svg. It's good to keep keep naming of files in small caps.

2024-01-20 07:40 UTC, RiyaMathew-11 commented on index.html
> +            <h3 class="text-center"><span class="text-blue">FOSS United</span> | Campus Logo Generator</h3>
Same heading as above

2024-01-20 07:40 UTC, RiyaMathew-11 commented on index.html
> +                    <button type="button" id="toggleColor" class="btn btn-block btn-dark shadow-sm">Dark Theme</button>
<img width="478" alt="Screenshot 2024-01-20 at 1 05 16 PM" src="https://github.com/fossunited/logo-generator/assets/60656677/411354ab-992a-46ef-9493-4e716ba0fd24">

The dark theme logo is different in colors. https://github.com/fossunited/logo-generator/blob/main/assets/fossclub_logo_dark.svg. Check this link for the logo, you can take the dark theme horizontal logo version from the Figma file too.

2024-01-20 07:40 UTC, RiyaMathew-11 commented on assets/favicon.ico
This file isn't needed. So can remove this.

2024-01-20 10:18 UTC, rohansh-tty commented on scripts/Horizontal Stacked Logo.svg
I was using it to debug, but don't need it anymore

2024-01-20 10:20 UTC, rohansh-tty commented on assets/favicon.ico
Deleting this file. I have not updated social links of FOSS United in the page, can you share i.e. Facebook, Twitter and Instagram links?

2024-01-22 07:39 UTC, RiyaMathew-11 requested changes

2024-01-22 07:39 UTC, RiyaMathew-11 commented on assets/favicon.ico
Instead of Facebook, keep Github. 
And instead of Instagram - put forum: https://forum.fossunited.org/
Twitter: https://twitter.com/FOSSUnited

2024-01-22 07:39 UTC, RiyaMathew-11 commented on index.html
> +    <title>FOSS United | Campus Logo Generator</title>
I can't seem to view the change. Can you commit again?

2024-01-22 07:39 UTC, RiyaMathew-11 commented on index.html
> +            <h3 class="text-center"><span class="text-blue">FOSS United</span> | Campus Logo Generator</h3>
Same as above, do push the change before resolving.

2024-01-22 07:39 UTC, RiyaMathew-11 commented on index.html
> +                    <button type="button" id="toggleColor" class="btn btn-block btn-dark shadow-sm">Dark Theme</button>
Do push the change before resolving too.

2024-01-22 07:39 UTC, RiyaMathew-11 commented on index.html
> +                    Created with <i class="fa fa-heart"></i> by FOSS United.
Let's edit the footer section a bit. 
Created with <i class="fa fa-heart"></i> by FOSS United => Inspired from `TinkerHub Campus Logo Generator` - hyperlinked to the TinkerHub logo generator repo.

2024-01-22 07:39 UTC, RiyaMathew-11 commented on scripts/Horizontal Stacked Logo.svg
Sure, then let's delete this file as well

2024-01-26 12:34 UTC, RiyaMathew-11 commented on index.html
The default opening of the site in light mode, somehow shows a different logo shade, it becomes proper while toggling to dark theme and then to light theme. 

<img width="922" alt="Screenshot 2024-01-26 at 6 00 35 PM" src="https://github.com/fossunited/logo-generator/assets/60656677/17a53db3-f2a6-47d7-b89c-d6981d8f37ea">

Can you try fixing it ? @rohansh-tty

2024-01-26 12:36 UTC, RiyaMathew-11 commented on assets/favicon.ico
Let's add Github too ? @rohansh-tty

2024-07-08 18:12 UTC, closed without merging